spring:
  application:
    name: auth-service
  #database
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/ggp_core
      username: root
      password: root
      connection-timeout: 30000
      idle-timeout: 20000
      max-lifetime: 25000
      minimum-idle: 10
      maximum-pool-size: 20
      leak-detection-threshold: 10000
      validation-timeout: 5000
      connection-test-query: SELECT 1
      jpa:
        show-sql: false
        properties:
          hibernate:
            order_inserts: true
            order_updates: true
            jdbc:
              batch_size: 1000
              fetch_size: 1000
              batch_versioned_data: true
            ddl-auto: none
            dialect: org.hibernate.dialect.MariaDBDialect
            naming:
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# swagger
springdoc:
  swagger-ui:
    path: /api-docs
    disable-swagger-default-url: true
  api-docs:
    path: /api-doc

server.port: 12000

security.secret: d51182515322005583d4aca915a176d75961a807

